export const packages = [
  {
    id: 1,
    name: "@mui/material",
    category: "UI",
    description:
      "Material UI is a comprehensive library of components that features our implementation of Google's Material Design system.",
    latest_version: "4.5",
    install_command: "npm i @mui/material",
    docs: "https://mui.com/material-ui/",
    image:
      "https://yt3.googleusercontent.com/bAPgcc0NUsnRyyikb_X6cz4Wdv4vFGZ0PvdAZs6dHgeMjXcau5AM7aFqdFxzP_UBXlbwiBg4=s900-c-k-c0x00ffffff-no-rj",
    repository: "https://github.com/mui/material-ui",
    weekly_downloads: "50,000",
    license: "MIT",
    size: "1.5MB",
    total_files: 1000,
  },
  {
    id: 2,
    name: "antd",
    category: "UI",
    description: "An enterprise-class UI design language and React UI library.",
    latest_version: "5.18.0",
    install_command: "npm i antd",
    docs: "https://ant.design/",
    image:
      "https://static-00.iconduck.com/assets.00/ant-design-icon-512x512-xbdsnx83.png",
    repository: "https://github.com/ant-design/ant-design",
    weekly_downloads: "11,39,675",
    license: "MIT",
    size: "45.4 MB",
    total_files: 3623,
  },
  {
    id: 3,
    name: "semantic-ui-react",
    category: "UI",
    description:
      "Semantic UI React is the official React integration for Semantic UI.",
    latest_version: "2.1.5",
    install_command: "npm i semantic-ui-react",
    docs: "https://react.semantic-ui.com/",
    image: "https://react.semantic-ui.com/logo.png",
    repository: "https://github.com/Semantic-Org/Semantic-UI-React",
    weekly_downloads: "1,99,583",
    license: "MIT",
    size: "2.9 MB",
    total_files: 1194,
  },
  {
    id: 4,
    name: "react-bootstrap",
    category: "UI",
    description: "The most popular front-end framework, rebuilt for React.",
    latest_version: "2.10.0",
    install_command: "npm i react-bootstrap",
    docs: "https://react-bootstrap.github.io/",
    image: "https://react-bootstrap.github.io/img/logo.svg",
    repository: "https://github.com/react-bootstrap/react-bootstrap",
    weekly_downloads: "9,88,269",
    license: "MIT",
    size: "1.47 MB",
    total_files: 735,
  },
  {
    id: 5,
    name: "office-ui-fabric-react",
    category: "UI",
    description:
      "The React-based front-end framework for building web experiences.",
    latest_version: "7.204.0",
    install_command: "npm i office-ui-fabric-react",
    docs: "https://react-bootstrap.github.io/",
    image: "https://cdn.buttercms.com/szRAUQ7tTaurKL95NS9x",
    repository: "https://github.com/microsoft/fluentui",
    weekly_downloads: "49,777",
    license: "MIT",
    size: "37.7 MB",
    total_files: 7147,
  },
  {
    id: 6,
    name: "reactstrap",
    category: "UI",
    description: "Stateless React Components for Bootstrap 5.",
    latest_version: "9.2.2",
    install_command: "npm i reactstrap",
    docs: "https://reactstrap.github.io/?path=/story/home-installation--page",
    image: "https://reactstrap.github.io/logo.svg",
    repository: "https://github.com/reactstrap/reactstrap",
    weekly_downloads: "3,74,895",
    license: "MIT",
    size: "2.19 MB",
    total_files: 604,
  },

  {
    id: 7,
    name: "blueprintjs/core",
    category: "UI",
    description: "Blueprint is a React UI toolkit for the web.",
    latest_version: "5.10.3",
    install_command: "npm i @blueprintjs/core",
    docs: "https://blueprintjs.com/docs/",
    image:
      "https://cloud.githubusercontent.com/assets/464822/20228152/d3f36dc2-a804-11e6-80ff-51ada2d13ea7.png",
    repository: "https://github.com/palantir/blueprint",
    weekly_downloads: "1,38,590",
    license: "Apache-2.0",
    size: "6.7 MB",
    total_files: 1813,
  },

  {
    id: 8,
    name: "chakra-ui/react",
    category: "UI",
    description:
      "Chakra UI is a simple, modular and accessible component library that gives you the building blocks you need to build your React applications.",
    latest_version: "2.8.2",
    install_command: "npm i @chakra-ui/react",
    docs: "https://v2.chakra-ui.com/",
    image: "https://avatars.githubusercontent.com/u/54212428?s=280&v=4",
    repository: "https://github.com/chakra-ui/chakra-ui",
    weekly_downloads: "4,46,636",
    license: "MIT",
    size: "40.2 kB",
    total_files: 17,
  },

  {
    id: 9,
    name: "grommet",
    category: "UI",
    description:
      "build responsive and accessible mobile-first projects for the web with an easy to use component library",
    latest_version: "2.38.0",
    install_command: "npm i grommet",
    docs: "https://v2.grommet.io/docs",
    image:
      "https://camo.githubusercontent.com/e72ce111e64bed1be672be587ebe1806af5ab628c37a6d62bff1f27d34944634/68747470733a2f2f76322e67726f6d6d65742e696f2f696d672f7374616b2d6875727261682e737667",
    repository: "https://github.com/grommet/grommet",
    weekly_downloads: "23,190",
    license: "Apache-2.0",
    size: "8.82 MB",
    total_files: 2333,
  },

  {
    id: 10,
    name: "redux",
    category: "State Management",
    description: "Redux is a predictable state container for JavaScript apps.",
    latest_version: "5.0.1",
    install_command: "npm i redux",
    docs: "https://redux.js.org/",
    image: "https://react-redux.js.org/img/redux.svg",
    repository: "https://github.com/reduxjs/redux",
    weekly_downloads: "81,42,063",
    license: "MIT",
    size: "290 kB",
    total_files: 28,
  },

  {
    id: 11,
    name: "react-redux",
    category: "State Management",
    description:
      "React Redux is the official React UI bindings layer for Redux. It lets your React components read data from a Redux store, and dispatch actions to the store to update state.",
    latest_version: "9.1.2",
    install_command: "npm i react-redux",
    docs: "https://react-redux.js.org/",
    image: "https://react-redux.js.org/img/redux.svg",
    repository: "https://github.com/reduxjs/react-redux",
    weekly_downloads: "63,23,220",
    license: "MIT",
    size: "740 kB",
    total_files: 17,
  },

  {
    id: 12,
    name: "mobx",
    category: "State Management",
    description: "Simple, scalable state Management.",
    latest_version: "6.12.3",
    install_command: "npm i mobx",
    docs: "https://mobx.js.org/README.html",
    image: "https://mobx.js.org/assets/mobx.png",
    repository: "https://github.com/mobxjs/mobx",
    weekly_downloads: "12,71,545",
    license: "MIT",
    size: "4.19 MB",
    total_files: 134,
  },

  {
    id: 13,
    name: "redux-thunk",
    category: "State Management",
    description:
      "Thunk middleware for Redux. It allows writing functions with logic inside that can interact with a Redux store's dispatch and getState methods.",
    latest_version: "3.1.0",
    install_command: "npm i redux-thunk",
    docs: "https://redux.js.org/usage/writing-logic-thunks",
    image:
      "https://miro.medium.com/v2/resize:fit:1400/1*5FcvZufrMDzs1ef63NjhXw.jpeg",
    repository: "https://github.com/reduxjs/redux-thunk",
    weekly_downloads: "43,14,543",
    license: "MIT",
    size: "26.8 kB",
    total_files: 9,
  },

  {
    id: 14,
    name: "redux-saga",
    category: "State Management",
    description: "An intuitive Redux side effect manager.",
    latest_version: "1.3.0",
    install_command: "npm i redux-thunk",
    docs: "https://redux-saga.js.org/",
    image: "https://redux-saga.js.org/img/Redux-Saga-Logo.png",
    repository: "https://github.com/redux-saga/redux-saga/tree/main",
    weekly_downloads: "9,61,001",
    license: "MIT",
    size: "221 kB",
    total_files: 21,
  },
  {
    id: 15,
    name: "redux-persist",
    category: "State Management",
    description: "Persist and rehydrate a redux store.",
    latest_version: "6.0.0",
    install_command: "npm i redux-persist",
    docs: "https://github.com/rt2zz/redux-persist#readme",
    image:
      "https://miro.medium.com/v2/resize:fit:1200/1*I_T-0UlbBW9aoUn6mZIhKA.png",
    repository: "https://github.com/rt2zz/redux-persist",
    weekly_downloads: "8,04,306",
    license: "MIT",
    size: "418 kB",
    total_files: 133,
  },
  {
    id: 16,
    name: "recoil",
    category: "State Management",
    description:
      "Recoil is an experimental state Management framework for React.",
    latest_version: "0.7.7",
    install_command: "npm i recoil",
    docs: "https://recoiljs.org/docs/introduction/core-concepts",
    image: "https://cdn.worldvectorlogo.com/logos/recoil-js.svg",
    repository: "https://github.com/facebookexperimental/Recoil",
    weekly_downloads: "4,70,832",
    license: "MIT",
    size: "2.21 MB",
    total_files: 104,
  },
  {
    id: 17,
    name: "zustand",
    category: "State Management",
    description:
      "A small, fast and scalable bearbones state-Management solution using simplified flux principles. Has a comfy API based on hooks, isn't boilerplatey or opinionated.",
    latest_version: "4.5.2",
    install_command: "npm i zustand",
    docs: "https://docs.pmnd.rs/zustand/getting-started/introduction",
    image: "https://github.com/pmndrs/zustand/raw/main/bear.jpg",
    repository: "https://github.com/pmndrs/zustand",
    weekly_downloads: "27,41,247",
    license: "MIT",
    size: "327 kB",
    total_files: 141,
  },
  {
    id: 18,
    name: "axios",
    category: "HTTP Client",
    description: "Promise based HTTP client for the browser and node.js.",
    latest_version: "1.7.2",
    install_command: "npm i axios",
    docs: "https://axios-http.com/docs/intro",
    image:
      "https://camo.githubusercontent.com/e56453737f3695a5d21d1393764ac1bc89032f5f4d2fc9fa486c980859347275/68747470733a2f2f6178696f732d687474702e636f6d2f6173736574732f6c6f676f2e737667",
    repository: "github.com/axios/axios",
    weekly_downloads: "4,02,83,215",
    license: "MIT",
    size: "2.08 MB",
    total_files: 86,
  },
  {
    id: 19,
    name: "apisauce",
    category: "HTTP Client",
    description: "Talking to APIs doesn't have to be awkward anymore.",
    latest_version: "3.0.1",
    install_command: "npm i apisauce",
    docs: "https://www.npmjs.com/package/apisauce",
    image: "https://avatars.githubusercontent.com/u/3902527?v=4",
    repository: "github.com/infinitered/apisauce",
    weekly_downloads: "78,071",
    license: "MIT",
    size: "33.1 kB",
    total_files: 6,
  },
  {
    id: 20,
    name: "react-fetch",
    category: "HTTP Client",
    description:
      "Fetch-react is a very small React Higher-Order Component that wraps the Fetch API in a declarative way.",
    latest_version: "0.4.0",
    install_command: "npm i fetch-react",
    docs: "https://app.circleci.com/pipelines/github/AlexanderDzhoganov/fetch-react",
    image: "https://www.patterns.dev/img/reactjs/react-logo@3x.svg",
    repository: "https://github.com/alexanderdzhoganov/fetch-react",
    weekly_downloads: "1,688",
    license: "MIT",
    size: "10.3 kB",
    total_files: 5,
  },
  {
    id: 21,
    name: "superagent",
    category: "HTTP Client",
    description:
      "Small progressive client-side HTTP request library, and Node.js module with the same API, supporting many high-level HTTP client features. Maintained for Forward Email and Lad.",
    latest_version: "9.0.2",
    install_command: "npm i superagent",
    docs: "https://www.npmjs.com/package/superagent",
    image:
      "https://www.npmjs.com/npm-avatar/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdmF0YXJVUkwiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci83NzQ1ZDFmOTUxOWVjZGIxMTZjNWI3MGMzODg2MzM1MT9zaXplPTQ5NiZkZWZhdWx0PXJldHJvIn0.xHzOGbPV5QpoS7C1EfJfFmBpSNeOs1NAv7EvFc34QZw",
    repository: "github.com/ladjs/superagent",
    weekly_downloads: "73,33,031",
    license: "MIT",
    size: "526 kB",
    total_files: 20,
  },
  {
    id: 22,
    name: "formik",
    category: "Form Handling",
    description: "Build forms in React, without the tears.",
    latest_version: "2.4.6",
    install_command: "npm i formik",
    docs: "https://formik.org/",
    image:
      "https://user-images.githubusercontent.com/4060187/61057426-4e5a4600-a3c3-11e9-9114-630743e05814.png",
    repository: "github.com/jaredpalmer/formik",
    weekly_downloads: "26,84,595",
    license: "Apache-2.0",
    size: "583 kB",
    total_files: 21,
  },
  {
    id: 23,
    name: "react-hook-form",
    category: "Form Handling",
    description:
      "Performant, flexible and extensible forms with easy-to-use validation.",
    latest_version: "7.51.5",
    install_command: "npm i react-hook-form",
    docs: "https://react-hook-form.com/",
    image:
      "https://raw.githubusercontent.com/react-hook-form/react-hook-form/master/docs/logo.png",
    repository: "https://github.com/react-hook-form/react-hook-form",
    weekly_downloads: "52,32,387",
    license: "MIT",
    size: "901 kB",
    total_files: 310,
  },
  {
    id: 24,
    name: "final-form",
    category: "Form Handling",
    description: "Handling forms haven't been easy before",
    latest_version: "4.20.10",
    install_command: "npm i final-form",
    docs: "https://final-form.org/",
    image:
      "https://raw.githubusercontent.com/final-form/final-form/HEAD/banner.png",
    repository: "github.com/final-form/final-form",
    weekly_downloads: "4,34,958",
    license: "MIT",
    size: "194 kB",
    total_files: 14,
  },
  {
    id: 25,
    name: "react-forms",
    category: "Form Handling",
    description:
      "React Forms library provides a set of tools for React to handle form rendering and validation.",
    latest_version: "1.0.0-rc6",
    install_command: "npm i react-forms",
    docs: "https://www.npmjs.com/package/react-forms",
    image:
      "https://lh3.googleusercontent.com/00hjufFKhWveAIuUfk5CfBL4FI0I4TdFMJ0KunpCPr1SMFDcAYM8q6g3vrW27DNVhCHyiDyXcjifJN2XTGwdNNWs7n0QAR8zePHALaRTQ9d7qBIL7lBGtw5XeEvbvbN_s7r1oMaY",
    repository: "https://github.com/prometheusresearch/react-forms",
    weekly_downloads: "109",
    license: "MIT",
    size: "2.02 MB",
    total_files: 236,
  },
  {
    id: 26,
    name: "@material-ui/icons",
    category: "Icons",
    description:
      "This package provides the Google Material icons packaged as a set of React components.",
    latest_version: "4.11.3",
    install_command: "npm i @material-ui/icons",
    docs: "https://mui.com/",
    image: "https://mui.com/static/blog/material-ui-is-now-mui/intro.png",
    repository: "github.com/mui-org/material-ui",
    weekly_downloads: "9,25,334",
    license: "MIT",
    size: "10.2 MB",
    total_files: 16674,
  },
  {
    id: 27,
    name: "react-icons",
    category: "Icons",
    description:
      "Include popular icons in your React projects easily with react-icons, which utilizes ES6 imports that allows you to include only the icons that your project is using.",
    latest_version: "5.2.1",
    install_command: "npm i react-icons",
    docs: "https://react-icons.github.io/react-icons/",
    image:
      "https://raw.githubusercontent.com/react-icons/react-icons/master/react-icons.svg",
    repository: "https://github.com/mui/material-ui",
    weekly_downloads: "21,12,603",
    license: "MIT",
    size: "85 MB",
    total_files: 143,
  },
  {
    id: 28,
    name: "@heroicons/react",
    category: "Icons",
    description:
      "Beautiful hand-crafted SVG icons, by the makers of Tailwind CSS.",
    latest_version: "2.1.3",
    install_command: "npm i @heroicons/react",
    docs: "https://heroicons.com/",
    image:
      "https://raw.githubusercontent.com/tailwindlabs/heroicons/HEAD/.github/logo-light.svg",
    repository: "github.com/tailwindlabs/heroicons",
    weekly_downloads: "9,08,697",
    license: "MIT",
    size: "3.33 MB",
    total_files: 4735,
  },
  {
    id: 29,
    name: "react-dnd",
    category: "Other",
    description:
      "React DnD gives you a set of powerful primitives, but it does not contain any readymade components. It's lower level than jQuery UI or interact.js and is focused on getting the drag and drop interaction right, leaving its visual aspects such as axis constraints or snapping to you.",
    latest_version: "16.0.1",
    install_command: "npm i react-dnd",
    docs: "https://react-dnd.github.io/react-dnd/",
    image: "https://avatars.githubusercontent.com/u/25307599?s=200&v=4",
    repository: "https://github.com/react-dnd/react-dnd",
    weekly_downloads: "15,34,526",
    license: "MIT",
    size: "231 kB",
    total_files: 179,
  },
  {
    id: 30,
    name: "swr",
    category: "Other",
    description:
      "SWR (stale-while-revalidate) is a React Hooks library for data fetching. SWR is a strategy to first return the data from cache (stale), then send the fetch request (revalidate), and finally come with the up-to-date data.",
    latest_version: "2.2.5",
    install_command: "npm i swr",
    docs: "https://swr.vercel.app",
    image: "https://miro.medium.com/v2/resize:fit:1400/0*QJrp3bkSv9wdNcKd",
    repository: "https://github.com/vercel/swr",
    weekly_downloads: "18,67,973",
    license: "MIT",
    size: "620 kB",
    total_files: 50,
  },
  {
    id: 31,
    name: "recharts",
    category: "Other",
    description:
      "Recharts is a React-based library that leverages D3. js under the hood for high-quality charting capabilities. It offers a collection of customizable React components for building various charts.",
    latest_version: "2.12.7",
    install_command: "npm i recharts",
    docs: "https://recharts.org/en-US/",
    image:
      "https://miro.medium.com/v2/resize:fit:1400/format:webp/1*SNiXLLhxrM5DBVLuBC9tvQ.png",
    repository: "https://github.com/recharts/recharts",
    weekly_downloads: "13,61,152",
    license: "MIT",
    size: "4.65MB",
    total_files: 291,
  },
  {
    id: 32,
    name: "chart.js",
    category: "Other",
    description:
      "Chart.js provides a set of frequently used chart types, plugins, and customization options. In addition to a reasonable set of built-in chart types, you can use additional community-maintained chart types . On top of that, it’s possible to combine several chart types into a mixed chart (essentially, blending multiple chart types into one on the same canvas).",
    latest_version: "4.4.3",
    install_command: "npm i chart.js",
    docs: "https://www.chartjs.org/",
    image:
      "https://camo.githubusercontent.com/98248b1bf462485aa41895e496c77664244583c89327baffb9dfa5af3a55ca89/68747470733a2f2f7777772e63686172746a732e6f72672f6d656469612f6c6f676f2d7469746c652e737667",
    repository: "https://github.com/chartjs/Chart.js",
    weekly_downloads: "27,00,532",
    license: "MIT",
    size: "4.93MB",
    total_files: 114,
  },
  {
    id: 33,
    name: "@blueprintjs/core",
    category: "Other",
    description:
      "Blueprint is a React-based UI toolkit for the web. It is optimized for building complex, data-dense web interfaces for desktop applications which run in modern browsers.",
    latest_version: "5.10.3",
    install_command: "npm i @blueprintjs/core",
    docs: "https://blueprintjs.com/docs/",
    image:
      "https://cloud.githubusercontent.com/assets/464822/20228152/d3f36dc2-a804-11e6-80ff-51ada2d13ea7.png",
    repository: "https://github.com/palantir/blueprint",
    weekly_downloads: "1,38,590",
    license: "MIT",
    size: "6.7MB",
    total_files: 1813,
  },
  {
    id: 34,
    name: "react-virtualized",
    category: "Other",
    description:
      "React components for efficiently rendering large lists and tabular data.",
    latest_version: "9.22.5",
    install_command: "npm i react-virtualized",
    docs: "http://bvaughn.github.io/react-virtualized/#/components/List",
    image:
      "https://cloud.githubusercontent.com/assets/29597/11737732/0ca1e55e-9f91-11e5-97f3-098f2f8ed866.png",
    repository: "https://github.com/bvaughn/react-virtualized",
    weekly_downloads: "10,36,653",
    license: "MIT",
    size: "2.2MB",
    total_files: 251,
  },
  {
    id: 35,
    name: "rsuite",
    category: "Other",
    description:
      "React Suite is a set of React components. It is committed to providing high-quality and comprehensive React components to help developers quickly build web applications.",
    latest_version: "5.64.0",
    install_command: "npm i rsuite",
    docs: "https://rsuitejs.com",
    image:
      "https://user-images.githubusercontent.com/1203827/65102389-7be3f100-d9fd-11e9-859e-ae9617ed2f91.png",
    repository: "https://github.com/rsuite/rsuite ",
    weekly_downloads: "69,160",
    license: "MIT",
    size: "24.6MB",
    total_files: 2804,
  },
  {
    id: 36,
    name: "tailwindcss",
    category: "Other",
    description:
      "Tailwind CSS is a utility-first CSS framework for rapidly building custom designs. It provides low-level utility classes that let you build completely custom designs without ever leaving your HTML.",
    latest_version: "3.4.3",
    install_command: "npm i tailwindcss",
    docs: "https://tailwindcss.com/docs",
    image:
      "https://raw.githubusercontent.com/tailwindlabs/tailwindcss/HEAD/.github/logo-light.svg",
    repository: "https://github.com/tailwindlabs/tailwindcss",
    weekly_downloads: "70,14,379",
    license: "MIT",
    size: "5.51MB",
    total_files: 252,
  },
];
